#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

workling = "vendor/plugins/workling/script/listen.rb"
options = {
  :app_name   => "workling",
  :ARGV       => ARGV,
  :dir_mode   => :normal,
  :dir        => 'log',
  :multiple   => false,
  :backtrace  => true,
  :monitor    => true
}

Daemons.run(workling, options)